//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRooms_Backup_20250819_103317
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int RoomId { get; set; }
        public decimal PriceAgreed { get; set; }
        public string Notes { get; set; }
    }
}
