//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractExtensionHistory
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public System.DateTime ExtendedAt { get; set; }
        public Nullable<System.DateTime> OldEndDate { get; set; }
        public Nullable<System.DateTime> NewEndDate { get; set; }
        public Nullable<int> ExtendMonths { get; set; }
        public string Note { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
