//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeExpens
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public string ReferenceNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual IncomeExpenseCategory IncomeExpenseCategory { get; set; }
        public virtual Room Room { get; set; }
    }
}
