//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string Note { get; set; }
        public int ContractId { get; set; }
        public Nullable<int> UtilityBillId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual UtilityBill UtilityBill { get; set; }
    }
}
