//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.ContractRooms = new HashSet<ContractRoom>();
            this.ContractTenants = new HashSet<ContractTenant>();
            this.UtilityBills = new HashSet<UtilityBill>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Area { get; set; }
        public int Floor { get; set; }
        public int RoomNumber { get; set; }
        public decimal DefaultPrice { get; set; }
        public bool HasAirCondition { get; set; }
        public bool HasFridge { get; set; }
        public bool IsOccupied { get; set; }
        public bool HasWaterHeater { get; set; }
        public bool HasBed { get; set; }
        public bool HasWardrobe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractRoom> ContractRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTenant> ContractTenants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilityBill> UtilityBills { get; set; }
    }
}
