//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilityBill
    {
        public int Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int ContractId { get; set; }
        public int WaterIndexStart { get; set; }
        public int WaterIndexEnd { get; set; }
        public decimal ElectricityAmount { get; set; }
        public decimal WaterAmount { get; set; }
        public decimal RentAmount { get; set; }
        public decimal ExtraCharge { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalAmount { get; set; }
        public string BillNote { get; set; }
        public string BillStatus { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
