//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CompanyRoomDetails
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string TaxCode { get; set; }
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public decimal PriceAgreed { get; set; }
        public string EmployeeList { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
    }
}
