//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContractDetails
    {
        public int ContractId { get; set; }
        public string ContractType { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal ElectricityPrice { get; set; }
        public decimal WaterPrice { get; set; }
        public string Note { get; set; }
        public string CompanyName { get; set; }
        public string TaxCode { get; set; }
        public string Representative { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public Nullable<decimal> TotalMonthlyRent { get; set; }
        public Nullable<int> TotalTenants { get; set; }
    }
}
