//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RoomStatus
    {
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public string Area { get; set; }
        public int Floor { get; set; }
        public decimal DefaultPrice { get; set; }
        public bool IsOccupied { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string ContractType { get; set; }
        public string ContractStatus { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RoomStatus { get; set; }
        public string CustomerName { get; set; }
        public string Tenants { get; set; }
        public Nullable<int> TenantCount { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
    }
}
