//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaTroAnCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterIndex
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int WaterReading { get; set; }
    }
}
